name: CI

on:
  push:
    # branches:
    #   - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test MacOS
    runs-on: macOS-26
    timeout-minutes: 30
    env:
      DEVELOPER_DIR: /Applications/Xcode_26.2.app
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=iOS Simulator,name=iPhone 17e"
    steps:
      - uses: actions/checkout@v5
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -skipMacroValidation -scheme swift-raae-Package -destination "${{ matrix.destination }}" test | xcbeautify

  linux:
    name: Test Linux
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container: swift:6.1
    steps:
      - uses: actions/checkout@v5
      - name: swift test
        run: swift test
